app_name = "go-microservice"
version = "1.0.0"

# Currency feed URL
feed_url = "https://www.bank.lv/vk/ecb_rss.xml"

[http]
address = "0.0.0.0:3035"
rate_limit = 120

[mysql]
address = "tcp(192.168.1.69:3306)"
database = "go_microservice_test"
user = "root"
password = "12345678"
pool_size = 5

